name: Whisper2
options:
  bundleIdPrefix: com.aiakademiturkiye
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"
  generateEmptyDirectories: true

packages:
  TweetNacl:
    url: https://github.com/bitmark-inc/tweetnacl-swiftwrap.git
    from: "1.0.0"
  WebRTC:
    url: https://github.com/stasel/WebRTC.git
    from: "125.0.0"

targets:
  Whisper2:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Core
      - path: Crypto
      - path: Domain
      - path: Networking
      - path: Services
      - path: Storage
      - path: UI
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aiakademiturkiye.whisper2
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: Whisper2.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: KX5N2U5RA2
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
    dependencies:
      - package: TweetNacl
      - package: WebRTC
    entitlements:
      path: Whisper2.entitlements
    info:
      path: Info.plist

  Whisper2Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Whisper2
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aiakademiturkiye.whisper2.tests
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: KX5N2U5RA2
