# Whisper2 iOS App
# Bundle ID: com.aiakademiturkiye.whisper2
# Team ID: KX5N2U5RA2

platform :ios, '17.0'
use_frameworks!

target 'Whisper2' do
  # WebRTC - community maintained (stasel/WebRTC)
  pod 'WebRTC-SDK', '~> 125.0'

  # TweetNacl - NaCl crypto library for Swift
  pod 'TweetNacl', '~> 1.0.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      # Build only for arm64 device (exclude simulator)
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      # Disable module verifier for TweetNacl (umbrella header issue)
      if target.name == 'TweetNacl'
        config.build_settings['ENABLE_MODULE_VERIFIER'] = 'NO'
      end
      # Disable dSYM for WebRTC (prebuilt framework has no debug symbols)
      if target.name == 'WebRTC-SDK'
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
      end
    end
  end

  installer.pods_project.build_configurations.each do |config|
    config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
  end

  # Fix TweetNacl umbrella header include style
  umbrella_path = 'Pods/Target Support Files/TweetNacl/TweetNacl-umbrella.h'
  if File.exist?(umbrella_path)
    text = File.read(umbrella_path)
    new_text = text.gsub(/#import "TweetNacl.h"/, '#import <TweetNacl/TweetNacl.h>')
    File.write(umbrella_path, new_text)
  end
end
