name: Whisper2

options:
  bundleIdPrefix: com.aiakademiturkiye
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    DEVELOPMENT_TEAM: KX5N2U5RA2
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "25"

targets:
  Whisper2:
    type: application
    platform: iOS
    sources:
      - path: App
        type: group
      - path: Core
        type: group
      - path: Crypto
        type: group
      - path: Models
        type: group
      - path: Protocol
        type: group
      - path: Services
        type: group
      - path: ViewModels
        type: group
      - path: Views
        type: group
      - path: Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: Whisper2.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.aiakademiturkiye.whisper2
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SKIP_INSTALL: NO
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "Apple Development"
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "Apple Distribution"
          PROVISIONING_PROFILE_SPECIFIER: whisper2
    preBuildScripts:
      - name: "Increment Build Number"
        script: |
          #!/bin/bash
          buildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "${PROJECT_DIR}/Info.plist")
          buildNumber=$(($buildNumber + 1))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "${PROJECT_DIR}/Info.plist"
          echo "Build number incremented to $buildNumber"
        showEnvVars: false
