-keep class com.sun.jna.** { *; }
-keep class com.goterl.lazysodium.** { *; }
-keepclasseswithmembernames class * { native <methods>; }
-keep class com.whisper2.app.data.network.** { *; }
-keep class com.whisper2.app.domain.model.** { *; }
-keep class org.webrtc.** { *; }
